"""Regenerate the bundled ``cuvis_ai_catalog.yaml`` from cuvis-ai's manifest.

The UI ships ``cuvis_ai_catalog.yaml`` as the default plugin manifest loaded at
startup (see ``cuvis_ai_ui/settings/plugins.py``). Its ``capabilities:`` list
mirrors the canonical node catalog in cuvis-ai's
``configs/plugins/cuvis_ai_builtin.yaml``, but under the UI's git source
(``repo``/``tag``) instead of a local ``path`` so the bundled gRPC server can
clone + import ``cuvis_ai.*`` without a local checkout.

One file is one bare plugin manifest: a logical ``name``, a source, and the
``capabilities`` it provides (no ``plugins:`` wrapper).

Run after the upstream manifest changes (nodes added/removed, schema bumps):

    uv run python scripts/regenerate_catalog.py
    uv run python scripts/regenerate_catalog.py --tag v0.7.4

Port specs are normalised to the current port-spec shape — one spec per port
plus a ``variadic`` flag (fan-in) — so the output stays valid even if the
upstream manifest is still in the older list-of-specs form. The normalisation is
idempotent, so re-running against an already-single-spec manifest is a no-op.
"""

from __future__ import annotations

from pathlib import Path

import click
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_DST = REPO_ROOT / "cuvis_ai_catalog.yaml"
# cuvis-ai sits beside cuvis-ai-ui under the same parent, mirroring the editable
# cuvis-ai-schemas source path in pyproject.toml ([tool.uv.sources]).
DEFAULT_SRC = (
    REPO_ROOT.parent.parent
    / "cuvis-ai"
    / "cuvis-ai"
    / "configs"
    / "plugins"
    / "cuvis_ai_builtin.yaml"
)
DEFAULT_REPO = "https://github.com/cubert-hyperspectral/cuvis-ai.git"
DEFAULT_TAG = "v0.7.3"

HEADER = """# cuvis-ai builtin plugin manifest (Cuvis.AI UI installer default)
#
# Loaded at UI startup via the LoadPlugin RPC (one call per manifest) so the
# bundled gRPC server can resolve `cuvis_ai.node.*` classes without a separate
# local checkout. LoadPlugin registers each as catalog metadata (it does not
# install); the node palette is populated straight from the `capabilities:`
# entries below.
#
# One file is one bare plugin manifest: a logical `name`, a source
# (`repo` + `tag` or `path`), and the `capabilities` it provides.
#
# Generated by scripts/regenerate_catalog.py from cuvis-ai's
# configs/plugins/cuvis_ai_builtin.yaml. Do not edit by hand: re-run the script
# (pass --tag for a new cuvis-ai release) when nodes change upstream.
"""


def _collapse(specs: dict | None, *, is_input: bool) -> dict:
    """Collapse a ``{port: spec|[specs]}`` map to one ``CatalogPortSpec`` per port.

    A multi-element list marks a fan-in (variadic) input port; outputs are never
    variadic. Already-single dict values pass through unchanged, so the transform
    is idempotent against an already-single-spec manifest.
    """
    out: dict = {}
    for port, value in (specs or {}).items():
        if isinstance(value, list):
            if not value:
                continue
            spec = dict(value[0])
            if is_input and len(value) > 1:
                spec["variadic"] = True
            out[port] = spec
        else:
            out[port] = value
    return out


def build_manifest(src: Path, repo: str, tag: str) -> dict:
    """Read the upstream bare manifest and build the UI's git-sourced manifest dict."""
    data = yaml.safe_load(src.read_text(encoding="utf-8"))
    name = data["name"]
    capabilities = data["capabilities"]
    for entry in capabilities:
        if "input_specs" in entry:
            entry["input_specs"] = _collapse(entry["input_specs"], is_input=True)
        if "output_specs" in entry:
            entry["output_specs"] = _collapse(entry["output_specs"], is_input=False)
    return {"name": name, "repo": repo, "tag": tag, "capabilities": capabilities}


@click.command()
@click.option(
    "--src",
    type=click.Path(path_type=Path),
    default=DEFAULT_SRC,
    show_default=True,
    help="Upstream cuvis_ai_builtin.yaml to mirror.",
)
@click.option(
    "--dst",
    type=click.Path(path_type=Path),
    default=DEFAULT_DST,
    show_default=True,
    help="Catalog yaml to write.",
)
@click.option(
    "--repo",
    default=DEFAULT_REPO,
    show_default=True,
    help="Git repo URL for the bundled clone.",
)
@click.option(
    "--tag",
    default=DEFAULT_TAG,
    show_default=True,
    help="Git tag (cuvis-ai release) to pin.",
)
def main(src: Path, dst: Path, repo: str, tag: str) -> None:
    """Regenerate the bundled cuvis_ai_catalog.yaml from cuvis-ai's manifest."""
    if not src.exists():
        raise click.ClickException(f"Upstream manifest not found: {src}")

    manifest = build_manifest(src, repo, tag)
    body = yaml.safe_dump(
        manifest, sort_keys=False, default_flow_style=False, allow_unicode=True, width=4096
    )
    dst.write_text(HEADER + body, encoding="utf-8")
    nodes = len(manifest["capabilities"])
    click.echo(f"Wrote {dst} ({nodes} nodes, tag {tag})")


if __name__ == "__main__":
    main()
