"""Regenerate the bundled ``cuvis_ai_catalog.yaml`` from cuvis-ai's manifest.

The UI ships ``cuvis_ai_catalog.yaml`` as the default plugin manifest loaded at
startup (see ``cuvis_ai_ui/settings/plugins.py``). Its ``provides:`` list mirrors
the canonical node catalog in cuvis-ai's ``configs/plugins/cuvis_ai_builtin.yaml``,
but under the UI's git source (``repo``/``tag``) instead of a local path so the
bundled gRPC server can clone + import ``cuvis_ai.*`` without a local checkout.

Run after the upstream manifest changes (nodes added/removed, schema bumps):

    uv run python tools/regenerate_catalog.py
    uv run python tools/regenerate_catalog.py --tag v0.7.4

Port specs are normalised to the current ``CatalogPortSpec`` shape — one spec per
port plus a ``variadic`` flag (fan-in) — so the output stays valid even if the
upstream manifest is still in the older list-of-specs form. The normalisation is
idempotent, so re-running against an already-single-spec manifest is a no-op.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_DST = REPO_ROOT / "cuvis_ai_catalog.yaml"
# cuvis-ai sits beside cuvis-ai-ui under the same parent, mirroring the editable
# cuvis-ai-schemas source path in pyproject.toml ([tool.uv.sources]).
DEFAULT_SRC = (
    REPO_ROOT.parent.parent
    / "cuvis-ai"
    / "cuvis-ai"
    / "configs"
    / "plugins"
    / "cuvis_ai_builtin.yaml"
)
DEFAULT_REPO = "https://github.com/cubert-hyperspectral/cuvis-ai.git"
DEFAULT_TAG = "v0.7.3"

HEADER = """# cuvis-ai catalog plugin manifest (Cuvis.AI UI installer default)
#
# Loaded at UI startup via PluginService.LoadPlugins so the bundled gRPC server
# can resolve `cuvis_ai.node.*` classes without a separate local checkout.
# LoadPlugins registers this as inline-catalog metadata (it does not install);
# the node palette is populated straight from the `provides:` entries below.
#
# Generated by tools/regenerate_catalog.py from cuvis-ai's
# configs/plugins/cuvis_ai_builtin.yaml. Do not edit by hand: re-run the tool
# (pass --tag for a new cuvis-ai release) when nodes change upstream.
"""


def _collapse(specs: dict | None, *, is_input: bool) -> dict:
    """Collapse a ``{port: spec|[specs]}`` map to one ``CatalogPortSpec`` per port.

    A multi-element list marks a fan-in (variadic) input port; outputs are never
    variadic. Already-single dict values pass through unchanged, so the transform
    is idempotent against an already-single-spec manifest.
    """
    out: dict = {}
    for port, value in (specs or {}).items():
        if isinstance(value, list):
            if not value:
                continue
            spec = dict(value[0])
            if is_input and len(value) > 1:
                spec["variadic"] = True
            out[port] = spec
        else:
            out[port] = value
    return out


def build_manifest(src: Path, repo: str, tag: str) -> dict:
    """Read the upstream manifest and build the UI's git-sourced manifest dict."""
    data = yaml.safe_load(src.read_text(encoding="utf-8"))
    provides = data["plugins"]["cuvis_ai_builtin"]["provides"]
    for entry in provides:
        if "input_specs" in entry:
            entry["input_specs"] = _collapse(entry["input_specs"], is_input=True)
        if "output_specs" in entry:
            entry["output_specs"] = _collapse(entry["output_specs"], is_input=False)
    return {"plugins": {"cuvis_ai_builtin": {"repo": repo, "tag": tag, "provides": provides}}}


def main() -> None:
    """Parse args, regenerate the bundled catalog, and report what was written."""
    parser = argparse.ArgumentParser(description="Regenerate the bundled cuvis_ai_catalog.yaml.")
    parser.add_argument(
        "--src", type=Path, default=DEFAULT_SRC, help="upstream cuvis_ai_builtin.yaml"
    )
    parser.add_argument("--dst", type=Path, default=DEFAULT_DST, help="output catalog yaml")
    parser.add_argument("--repo", default=DEFAULT_REPO, help="git repo URL for the bundled clone")
    parser.add_argument("--tag", default=DEFAULT_TAG, help="git tag (cuvis-ai release)")
    args = parser.parse_args()

    if not args.src.exists():
        raise SystemExit(f"Upstream manifest not found: {args.src}")

    manifest = build_manifest(args.src, args.repo, args.tag)
    body = yaml.safe_dump(
        manifest, sort_keys=False, default_flow_style=False, allow_unicode=True, width=4096
    )
    args.dst.write_text(HEADER + body, encoding="utf-8")
    nodes = len(manifest["plugins"]["cuvis_ai_builtin"]["provides"])
    print(f"Wrote {args.dst} ({nodes} nodes, tag {args.tag})")


if __name__ == "__main__":
    main()
